### PR TITLE
AutoFlashcard Implementation

### PR DESCRIPTION
**Pull request by StarDylan**

### CODE REVIEW

**Review by Anamooz — APPROVED** [review]
Looks good to me thumbs up emoji

**Review by SanTran113 — APPROVED** [review]
I like how the cards show you which questions are right and which are wrong at the end of each question!!

**Review by nrojo1124 — APPROVED** [review]
LGTM, but you might want to be careful about in-place reassignment of the question answers from props. If the question data is pulled from a useState value, then the shuffle method will not properly update the array state. If it is not pulled from a useState value, then it's possible that the UI will not properly update to show the shuffled answers since React won't track updates to it. Alternative approach could be generating random order of indices for each question based on how many answers there are and then mapping over those.

**Comment by StarDylan** [comment]
> be careful about in-place reassignment of the question answers from props ... not pulled from a useState value, then it's possible that the UI will not properly update to show the shuffled answers since React won't track updates to it

Your right I completely missed that, I'll need to fix that

**Comment by StarDylan** [comment]
> LGTM, but you might want to be careful about in-place reassignment of the question answers from props. If the question data is pulled from a useState value, then the shuffle method will not properly update the array state. If it is not pulled from a useState value, then it's possible that the UI will not properly update to show the shuffled answers since React won't track updates to it. Alternative approach could be generating random order of indices for each question based on how many answers there are and then mapping over those.

Ok Fixed!

**Review by thekevinWHYuan — APPROVED** [review]
LGTM! Really like the UI change.

**Pull request merged**
